### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by jkroepke**
The changes on the comments coming from `go fmt`. I can rollback the whitespace changes, but this is incompatible with `go fmt`

### CODE REVIEW

**Comment by jkroepke** [comment]
@leoluk I would appreciate a review here.

**Comment by jkroepke** [comment]
@leoluk I would appreciate a review here.

**Comment by leoluk** [comment]
Apologies - missed the notification. Happy to merge if you re-open.

Also, https://github.com/leoluk/perflib_exporter/issues/25 :-)

**Comment by jkroepke** [comment]
@leoluk Sorry, I can't reopen this PR, since I deleted the fork repository.

**Pull request closed without merging**
