### PR TITLE
Fix PERF_COUNTER_BASE value

### LINKED ISSUE #16: IsBaseValue based on wrong constant?
In the parsing of `PerfCounterDef`, `IsBaseValue` is set like this:
https://github.com/leoluk/perflib_exporter/blob/e137d65289553940dff03f4bb83908c0acea069a/perflib/perflib.go#L340

Where is this constant taken from? In the sources I've found (for example [here](https://referencesource.microsoft.com/#System/compmod/microsoft/win32/NativeMethods.cs,742)), the constant used seems to be `PERF_DISPLAY_PERCENT`, while `PERF_COUNTER_BASE` is 0x00030000.

Are there multiple definitions of these constants, or is it wrong?

cc @bismarck

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #16

### CODE REVIEW

**Comment by carlpett** [comment]
Hm, actually - shouldn't these three checks be on the form `def.CounterType&flag == flag` rather than `def.CounterType&flag > 0`?

**Comment by carlpett** [comment]
It should. Updated the patch. 
@leoluk, could you take a look?

**Comment by carlpett** [comment]
@leoluk Any feedback on this?

**Comment by leoluk** [comment]
LGTM for both, thanks!

**Pull request merged**
